services:

  mongo:
    image: mongo
    container_name: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
        - MONGO_INITDB_DATABASE=cyberconseil

    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
          - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro


  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"

  web-php:
    image: php:fpm
    container_name: web-php
    environment:
      - API_URI=http://api:3000
    ports:
      - "9000:9000"
    volumes:
          - "./front:/var/www/html:ro"
   


  frontend:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./front:/var/www/html
      - ./config/server/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web-php

    links:
    - web-php


  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/server:consistent
    links:
      - mongo
    environment:
      - URL_MONGO=mongodb://api_user:api1234@mongo:27017/cyberconseil
  

